# Generated by Django 4.0.3 on 2023-02-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageItems', '0003_inventory_delete_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hwItems',
        ),
    ]
