# Generated by Django 4.0.3 on 2023-02-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageItems', '0004_delete_hwitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory',
            new_name='ItemInventory',
        ),
    ]
