# Generated by Django 4.0.3 on 2023-02-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageItems', '0005_rename_inventory_iteminventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemInventory',
        ),
    ]
