# Generated by Django 4.0.3 on 2023-02-08 23:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageItems', '0006_userdata_delete_iteminventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='birth_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='lname',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
    ]
