# Generated by Django 4.0.3 on 2023-02-09 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageItems', '0007_alter_userdata_birth_date_alter_userdata_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='birth_date',
            new_name='date_created',
        ),
    ]
