# Generated by Django 4.0.3 on 2023-02-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageItems', '0010_userdata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='category',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Student', 'Student'), ('Teacher', 'Teacher')], max_length=20, null=True),
        ),
    ]
